name: local_auth_example
description: Demonstrates how to use the local_auth plugin.

dependencies:
  flutter:
    sdk: flutter
  flutter_local_auth_invisible:
    path: ../

flutter:
  uses-material-design: true
